// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiJrsI--Hy2XJSV9F9QXd9u6wSubfD3tU',
    appId: '1:496957097579:web:f92b755d730c251bf6532e',
    messagingSenderId: '496957097579',
    projectId: 'device-streaming-511ab462',
    authDomain: 'device-streaming-511ab462.firebaseapp.com',
    storageBucket: 'device-streaming-511ab462.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3gmMEB4UL2H31gIrJK6ggxPWMabfPzug',
    appId: '1:496957097579:android:348191d9ac6e01e1f6532e',
    messagingSenderId: '496957097579',
    projectId: 'device-streaming-511ab462',
    storageBucket: 'device-streaming-511ab462.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ei7-JlGNfaiJlPdovezxVti2YJyu3bk',
    appId: '1:496957097579:ios:4c7191a704516961f6532e',
    messagingSenderId: '496957097579',
    projectId: 'device-streaming-511ab462',
    storageBucket: 'device-streaming-511ab462.firebasestorage.app',
    iosBundleId: 'com.example.sampleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5ei7-JlGNfaiJlPdovezxVti2YJyu3bk',
    appId: '1:496957097579:ios:4c7191a704516961f6532e',
    messagingSenderId: '496957097579',
    projectId: 'device-streaming-511ab462',
    storageBucket: 'device-streaming-511ab462.firebasestorage.app',
    iosBundleId: 'com.example.sampleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiJrsI--Hy2XJSV9F9QXd9u6wSubfD3tU',
    appId: '1:496957097579:web:2703f428d380c8f4f6532e',
    messagingSenderId: '496957097579',
    projectId: 'device-streaming-511ab462',
    authDomain: 'device-streaming-511ab462.firebaseapp.com',
    storageBucket: 'device-streaming-511ab462.firebasestorage.app',
  );

}